companies_fullx = [
'5 Star Stoves',
'Acacia Innovations',
'ADES Association pour le Développement de l\'Energie Solaire Suisse - Madagascar',
'African Clean Energy',
'African Energy Environment Saving Stoves & Construction Ltd.',
'ALMIGHTY SERVICES PLUS',
'Anega Energies Manufacturing PLC',
'ANT Stove Producer.',
'Applied Sunshine, LLC',
'Appropriate Energy Saving Technologies, Ltd.',
'ASAT Inc.',
'ATEC',
'Bboxx',
'BD Vision',
'Better world Innovations',
'Bidhaa Sasa',
'BioLite',
'BioMassters Limited',
'BLUE FLAME STOVES AS (LTD)',
'Bold Energy',
'BrightGreen Renewable Energy',
'Buenos Vecinos S.A.',
'BUN-CA',
'BURN Manufacturing',
'Burro,LLC',
'Carbon Roots',
'Circle Gas Ltd',
'CleanStar Ventures, LLC',
'Connected Energy Technologies',
'Consumer\'s Choice Limited',
'CookClean Ghana',
'C-Quest Capital LLC',
'D&E',
'Dazin',
'Dharma Life',
'Dona Dora',
'Eco Fuel Industries (BD)',
'Eco Group',
'Eco2librium Company Limited',
'Ecobora',
'EcoGen Limited',
'Ecosur Afrique',
'EcoZoom East Africa Ltd',
'Electrocook',
'Emerging Cooking Solutions',
'Envirofit International Inc.',
'Essmart',
'Feu vert Benin (Cooking Stove)',
'Filament Engineering Ltd.',
'FONBOL ENERGY',
'Frontier Markets',
'Fuego del Sol S.R.L.',
'Future Carbon Limited',
'Genete Taddesse Fuel Saving Production and Sales Enterprise',
'Ghana Cylinder Manufacturing Company Limited',
'GIVE LTD',
'GoSun',
'Green 66 Innovations',
'Green Bio Energy Ltd',
'Green Eco Solutions',
'Green Energy & Biofuels',
'Green Gold Liberia',
'Green Ker',
'GREEN LAND FATI GOLD SERVICES NIG. LTD',
'Greenway',
'Haines Solar Cookers',
'Hi-Z Technology',
'Homebiogas',
'ICS LUXUR COOK STOVE',
'ICSEA',
'Impact Carbon',
'Improved Cookstove Program in Laos PDR',
'Intellectual Capital Advisory Services',
'INTERGRATED STOVES AGENCY KENYA LIMITED(ISAKENYA LTD)',
'International Lifeline Fund',
'International Research and Development Africa Ltd',
'Inyenyeri',
'IRDA',
'Jaan Pakistan',
'Jitu renewabe energy ',
'Juntos Energy Solutions NFP',
'Kencoco Limited',
'King Biofuels',
'Klarisse Kenya Limited dba EzyLife Kenya',
'KOKO Networks',
'Kopernik',
'Lanzhou Huaneng',
'Lem Betiret RE Production & Distribution Enterprise',
'Life Engineering  ltd.',
'LivelyHoods',
'LPG BOTTLING',
'Luxur',
'Lynch Farms and General Supplies',
'Man and Man Enterprise Limited',
'Methano-Green Clean Energy',
'Micro Energy Credits',
'Microsol',
'Mimi Moto',
'M-KOPA Solar',
'Montals Engineering Enterprise',
'Mubende Stoves',
'Mwangaza Light',
'Nenu',
'NewLight Africa',
'Nile Bioeconomic Innovations Ltd',
'NoKooda Solution System Pvt. Ltd.',
'Novogaz',
'Oando',
'Obamastove',
'One Earth Designs',
'OSMER SARL',
'OTAGO',
'PALMIS Enèji',
'Paradigm Project',
'PayGas',
'PayGo Energy',
'phukaphuka construction',
'Picture Frames International',
'Potential Energy',
'Prakti',
'Prime Cookstoves AS',
'Principle Energy',
'Project Gaia ',
'Proyecto Mirador',
'Pura',
'Rahimafrooz Renewable Energy Limited (RREL)',
'Raising  Gabdho Foundation Ltd',
'Relief International',
'Roshan',
'RURAL SERVICES FOUNDATION',
'Sanivation',
'Santa Clara University',
'SCODE Limited',
'Self Employed Women\'s Association (SEWA)',
'Shubha Biomass Briquette Pvt. Ltd.',
'SimGas',
'Sistema.bio',
'Small and Medium Entrepreneurship Fundamentals (SME Funds)',
'Smart Trading Pvt Ltd ',
'Social Development Organization of Bangladesh (SDOB)',
'SOCO CLEAN COOKING',
'Solar Cookers International',
'Solar Energy Consulting & Construction Company (SECCCO)',
'Solar Sister Inc.',
'Solkamtech',
'Soluciones Apropriadas, S.A.',
'SOSAI RENEWABLE ENERGIES COMPANY LIMITED',
'SosteNica',
'SP ECO FUEL',
'SSM',
'Struggle Against Poverty',
'Sun Buckets',
'The Fusion Experience Kenya Limited',
'Tizazu Yerdaw Cook Stove Manufacturer',
'Toyola Energy Limited',
'trans care agencies',
'UGANDA STOVE MANUFACTURERS LIMITED',
'UltGas',
'Ultimate Gas Professionals Limited',
'UpEnergy',
'Venus',
'VidaGas',
'Village Infrastructure Angels',
'WANA ENERGY SOLUTIONS',
'Wisdom Energy Hub',
'Wisdom Innovations',
'WK Renewable Energy '
]

companies_extended = [
'Acacia Innovations',
'ATEC',
'Bboxx',
'Bidhaa Sasa',
'BioLite',
'BioMassters Limited',
'BURN Manufacturing',
'Circle Gas Ltd',
'Connected Energy Technologies',
'Emerging Cooking Solutions',
'Green 66 Innovations',
'Greenway',
'International Lifeline Fund',
'KOKO Networks',
'Mwangaza Light',
'Obamastove',
'OTAGO',
'PALMIS Enèji',
'PayGas',
'Sistema.bio',
'SP ECO FUEL',
'The Fusion Experience Kenya Limited'
]


 check_company_names().then(function(names){
	companies_full=names


var input = document.getElementById("business_name");
new Awesomplete(input, {list: companies_full});
document.getElementById('business_name').addEventListener('awesomplete-selectcomplete',function(){
// Script to run after selection is made

name = input.value

load_company_name_analysis(name).then(function(results){
	if(results ==1){
  	document.getElementById('login_key').style.display = 'block';
  	document.getElementById('new_company').style.display = 'none';
  }
  else{document.getElementById('login_key').style.display = 'none';
  	document.getElementById('new_company').style.display = 'block';}

})
//Only show login section if company name is in list

});
})


